"""Minimal instrumented agent skeleton — reports to Boidra Platform.

A LangGraph-style loop with one tool. The LLM step is a placeholder; replace `fake_llm` and
`example_tool` with your real logic. The span structure (invoke_agent → chat → execute_tool) is
what the dashboard renders as a trace. Generated by Boidra Platform's install-agent wizard.
"""

from __future__ import annotations

import otel_setup

AGENT_NAME = "test-agent"


def fake_llm(prompt: str) -> tuple[str, int, int]:
    """Placeholder LLM. Return (text, input_tokens, output_tokens). Swap in a real client."""
    return (f"I'll use the example tool for: {prompt}", 12, 8)


def example_tool(query: str) -> str:
    """Placeholder tool. Replace with a real MCP tool / function call."""
    return f"tool result for {query!r}"


def run(prompt: str) -> str:
    with otel_setup.invoke_agent_span(AGENT_NAME, prompt=prompt):
        text, tin, tout = None, 0, 0
        with otel_setup.chat_span("gpt-4o-mini", input_tokens=12, output_tokens=8):
            text, tin, tout = fake_llm(prompt)

        with otel_setup.execute_tool_span("example_tool", tool_type="function"):
            result = example_tool(prompt)

        with otel_setup.chat_span("gpt-4o-mini", input_tokens=tin, output_tokens=tout):
            final = f"{text}\n{result}"
        return final


if __name__ == "__main__":
    otel_setup.init(AGENT_NAME)
    try:
        print(run("hello, agent"))
    finally:
        otel_setup.flush()
