# Generated by Boidra Platform's install-agent wizard.
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Telemetry endpoint is provided by the platform (see manifest.yml / .env.example).
CMD ["python", "agent.py"]
