"""OpenTelemetry bootstrap + GenAI span helpers for Boidra Platform.

Configures a TracerProvider that exports over OTLP/HTTP to Boidra Platform's ingest, and exposes
context managers that create spans carrying the GenAI semantic-convention attributes the
dashboard reads:

  invoke_agent : gen_ai.operation.name=invoke_agent, gen_ai.agent.name, gen_ai.conversation.id
  chat         : gen_ai.operation.name=chat, gen_ai.request.model, gen_ai.usage.{input,output}_tokens
  execute_tool : gen_ai.operation.name=execute_tool, gen_ai.tool.name, gen_ai.tool.type

Wrap the REAL work (an LLM call, a tool invocation) in these so the spans are genuine.
Generated by Boidra Platform's install-agent wizard.
"""

from __future__ import annotations

import os
from contextlib import contextmanager

from opentelemetry import trace
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.trace import SpanKind, Status, StatusCode

DEFAULT_ENDPOINT = "http://localhost:3010"
_initialised = False


def init(service_name: str | None = None) -> None:
    """Install a global TracerProvider exporting to Boidra Platform. Call once per process."""
    global _initialised
    if _initialised:
        return
    name = service_name or os.environ.get("OTEL_SERVICE_NAME", "agent")
    endpoint = os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT", DEFAULT_ENDPOINT)
    exporter = OTLPSpanExporter(endpoint=f"{endpoint.rstrip('/')}/v1/traces")
    provider = TracerProvider(resource=Resource.create({"service.name": name}))
    provider.add_span_processor(BatchSpanProcessor(exporter))
    trace.set_tracer_provider(provider)
    _initialised = True


def tracer():
    return trace.get_tracer("agent")


def flush() -> None:
    provider = trace.get_tracer_provider()
    if hasattr(provider, "force_flush"):
        provider.force_flush()


@contextmanager
def invoke_agent_span(agent_name: str, *, conversation_id: str = "conv-1",
                      user_id: str = "user", tenant_id: str = "tenant", prompt: str | None = None):
    attrs = {
        "gen_ai.operation.name": "invoke_agent",
        "gen_ai.agent.name": agent_name,
        "gen_ai.conversation.id": conversation_id,
        "user.id": user_id,
        "sap.tenancy.tenant_id": tenant_id,
    }
    if prompt:
        attrs["gen_ai.prompt"] = prompt
    with tracer().start_as_current_span(f"invoke_agent {agent_name}",
                                        kind=SpanKind.SERVER, attributes=attrs) as span:
        yield span


@contextmanager
def chat_span(model: str, *, input_tokens: int = 0, output_tokens: int = 0):
    attrs = {
        "gen_ai.operation.name": "chat",
        "gen_ai.request.model": model,
        "gen_ai.usage.input_tokens": input_tokens,
        "gen_ai.usage.output_tokens": output_tokens,
    }
    with tracer().start_as_current_span(f"chat {model}",
                                        kind=SpanKind.CLIENT, attributes=attrs) as span:
        yield span


@contextmanager
def execute_tool_span(tool_name: str, *, tool_type: str = "function",
                      extension_name: str | None = None):
    attrs = {
        "gen_ai.operation.name": "execute_tool",
        "gen_ai.tool.name": tool_name,
        "gen_ai.tool.type": tool_type,
    }
    if extension_name:
        attrs["extension_name"] = extension_name
        attrs["extension_type"] = "tool"
    with tracer().start_as_current_span(f"execute_tool {tool_name}",
                                        kind=SpanKind.CLIENT, attributes=attrs) as span:
        try:
            yield span
        except Exception as e:  # noqa: BLE001
            span.set_status(Status(StatusCode.ERROR, str(e)))
            span.set_attribute("error", True)
            span.set_attribute("error.message", str(e))
            raise
